### ISSUE TITLE
Unable to fetch user wantlist

### ISSUE THREAD

**Issue by kacperente** [lionralfs/discogs-client#198]
Hi, first of all I would like to thank you for this package. I was able to integrate very smoothly with the authentication mechanism and a great advantage is that it has defined types! However, I encountered a problem. 

**Issue:**
The process of authenticating the user and retrieving their data using the `client.getIdentity()` method works fine but when I try to retrieve the wantlist using `client.user().wantlist().getReleases("my_username")` I get a `403` with an error:

`DiscogsError: You are not allowed to view this resource. Please authenticate as the owner to view this content.`

After more research, I came across this thread on the discogs forum: https://www.discogs.com/forum/thread/1032532
Looks like at some point discogs changed `oauth_signature_method` from `PLAINTEXT` to `HMAC-SHA1`. 

When I tested this in Insomnia by setting `oauth_consumer_key`, `oauth_consumer_secret`, `oauth_token_key`, `oauth_token_secret` and `oauth_signature_method` to `HMAC-SHA1` - everything works fine and I am able to download the wantlist for the logged-in user.

**Comment by lionralfs** [comment]
Hi, thanks for your elaborate report! I'm able to reproduce it, and it seems to be a related to a combination of two things:

1. The way the nonce is calculated (the latest comment in the thread you linked mentions an int <= MAX_INT)
2. The timestamp in `oauth_timestamp` is apparently expected to be of seconds, not milliseconds.

I'm not sure if this is a bug in the server implementation or whether we should change anything as a client (especially nr. 1 above). I'll investigate further when I have more time.

**Comment by lionralfs** [comment]
Hi @kacperente I just released an alpha version `v3.1.3-0`. Can you verify that the fix works? If it does I'll release `v3.1.3`.

**Comment by kacperente** [comment]
Hi @lionralfs.

It works like a charm! I'm now able to fetch the wantlist. Thanks for fixing the problem so quickly!

**Comment by lionralfs** [comment]
Glad I could help!

FYI: I just released version `3.1.3` which is essentially the same as `3.1.3-0`.
