### ISSUE TITLE
URI missing in getArtistReleases()

### ISSUE THREAD

**Issue by sergiocastrovale** [lionralfs/discogs-client#278]
If I call `getArtistReleases` I get the list of releases, but I am missing the `uri` from them. I do get it if I individually call `getRelease`, though. So if I want to catalogue all the `uri`s in a given discography, I would have to:

1. Search for the artist by name (1 query)
2. Search for the catalogue with `getArtistReleases` (n queries if multiple pages)
3. Iterate over every release and search `getRelease` (n queries).

This is an incredibly expensive thing just to get the catalogue from an artist.

Is this a problem from the base Discogs API?

**Comment by lionralfs** [comment]
Unfortunately that seems to be a limitation with the discogs API :(

I just checked and the [Artist Releases](https://www.discogs.com/developers/#page:database,header:database-artist-releases-get) endpoint only returns a `resource_url` which has the format `https://api.discogs.com/masters/<id>`.

To receive the uri (like https://www.discogs.com/release/26357174-Nickelback-The-Making-Of-This-Afternoon) the call to `getRelease` appears to be the way to go.
